<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
    <div class="post-list-wrapper blog-widget-recent">
	<div class="title-home-page">
		<span><?php echo $block->escapeHtml($block->getTitle()) ?></span>
	</div>
	
    <div class="owl-carousel">
        <?php foreach ($_postCollection as $_post) { ?>
			<?php
			$_postUrl  = $_post->getPostUrl();
			$_postName = $block->escapeHtml($_post->getTitle(), null, true);
			?>

            <div class="item">
				<div class="post-image static-image">
					<?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
						<img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>"/>
					</a>
					<?php } ?>
				</div>
				
				<div class="post-info">
					<div class="post-date">
						<span class="label-post"><?php echo __('Posted:') ?></span>
						<span class="value"><?php echo $_post->getPublishDate('Y-m-d') ?></span>
					</div>
					
					<div class="post-title">
						<a class="post-item-link"
                           href="<?php echo $_postUrl ?>">
							<?php echo $_postName; ?>
						</a>
					</div>
				</div>
			</div>
		<?php } ?>
    </div>
</div>
<?php } ?>