<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */
			echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php
	$viewMode        = 'grid';
	$image           = 'product_sidebar';
	$showDescription = false;
	$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$showWishlist    = true;
	$showCompare     = true;
	$showCart        = true;
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos    = $block->getPositioned();
	$tag_id = "sm_filterproducts_" . time() . rand() . "";

	$product_row = $this->_getConfig('product_row');
	$i           = 0;
	$count       = $_productCollection->count();
	?>

    <div id="<?php echo $tag_id; ?>" class="list-slider">
		<?php if (!empty($this->_getConfig('title_module'))) { ?>
            <div class="block-title">
			<span><?php echo $this->_getConfig('title_module'); ?></span>
		</div>
		<?php } ?>

		<?php
		if ($this->_getConfig('product_source') == 'countdown_products') {
			$dateTo = $this->_getConfig('date_to', '');
			?>
            <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
			<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
		</div>
		<?php } ?>

        <div class="owl-carousel">
			<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php foreach ($_productCollection as $_product) {
				$i++; ?>
				<?php if ($i % $product_row == 1 || $product_row == 1) { ?>
                    <div class="item product product-item">
				<?php } ?>
                <div class="item-inner clearfix">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>

					<?php // Product Image ?>
                    <div class="box-image">
							<a href="<?php /* @escapeNotVerified */
							echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>
						</div>
						
						<div class="product details product-item-details box-info">
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
                            <h2 class="product name product-name product-item-name">
								<a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
								   echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */
									echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h2>

							<?php /* @escapeNotVerified */
							echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>
						</div>

					<?php
					if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
						$specialToDate = $_product->getSpecialToDate();
						?>
                        <div class="deals-countdown clearfix" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
							<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
							<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
							<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
							<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
						</div>
					<?php } ?>
					</div>
				<?php if ($i % $product_row == 0 || $i == $count) { ?>
                    </div>
				<?php } ?>
			<?php } ?>
		</div>
    </div>

    <script type="text/javascript">
        require([
            'jquery',
            'owlcarousel'
        ], function ($) {
            var $element = $('#<?php echo $tag_id ?>');

            function CountDown(date, id) {
                dateNow = new Date();
                amount = date.getTime() - dateNow.getTime();
                delete dateNow;
                if (amount < 0) {
                    id.html("Now!");
                } else {
                    days = 0;
                    hours = 0;
                    mins = 0;
                    secs = 0;
                    out = "";
                    amount = Math.floor(amount / 1000);
                    days = Math.floor(amount / 86400);
                    amount = amount % 86400;
                    hours = Math.floor(amount / 3600);
                    amount = amount % 3600;
                    mins = Math.floor(amount / 60);
                    amount = amount % 60;
                    secs = Math.floor(amount);
                    $(".time-day .num-time", id).text(days);
                    $(".time-day .title-time", id).text(((days <= 1) ? "Day" : "Days"));
                    $(".time-hours .num-time", id).text(hours);
                    $(".time-hours .title-time", id).text(((hours <= 1) ? "Hour" : "Hours"));
                    $(".time-mins .num-time", id).text(mins);
                    $(".time-mins .title-time", id).text(((mins <= 1) ? "Min" : "Mins"));
                    $(".time-secs .num-time", id).text(secs);
                    $(".time-secs .title-time", id).text(((secs <= 1) ? "Sec" : "Secs"));
                    setTimeout(function () {
                        CountDown(date, id)
                    }, 1000);
                }
            }

            $(".deals-countdown", $element).each(function () {
                var timer = $(this).data('timer');
                var data = new Date(timer);
                CountDown(data, $(this));
            });

            $('#<?php echo $tag_id; ?> .owl-carousel').owlCarousel({
                loop: false,
                nav: false,
                dots: true,
                autoplay: false,
                autoplayHoverPause: true,
                margin: 30,
                responsive: {
                    0: {
                        items: 1
                    },
                    480: {
                        items: 1
                    },
                    768: {
                        items: 1
                    },
                    991: {
                        items: 1
                    },
                    1200: {
                        items: 1
                    }
                }
            });
        });
    </script>
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>
